name: build-rbxmk-studio

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux

          - os: macos-14
            platform: macos

          - os: windows-2022
            platform: windows

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Download Filament (windows only)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          curl -L https://github.com/google/filament/releases/download/v1.69.4/filament-v1.69.4-windows.tgz -o filament.tgz

          tar -xzf filament.tgz
          
          mv filament-* filament

          mv filament-* assets/filament-platform/win32/

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg

      - name: Install Qt
        run: vcpkg install qt

      - name: Configure
        run: >
          cmake -S . -B build -G Ninja
          -DPLATFORM=${{ matrix.platform }}
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/dist
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

      - name: Install
        run: cmake --install build

      - name: Zip (Unix)
        if: runner.os != 'Windows'
        run: zip -r app.zip dist

      - name: Zip (Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive dist app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rbxmk-studio-${{ runner.os }}
          path: app.zip
